name: Linters

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run RuboCop
        run: bundle exec rubocop
